name: Testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        sample: [flixel, openfl]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libvlc-dev libvlccore-dev

      - name: Installing Haxe Libraries
        run: |
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc.git ${{github.ref_name}} --quiet

      - name: Building Windows
        if: matrix.os == 'windows-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build windows -debug

      - name: Building MacOS
        if: matrix.os == 'macos-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build mac -debug

      - name: Building Linux
        if: matrix.os == 'ubuntu-latest'
        run: cd samples/${{matrix.sample}} && haxelib run lime build linux -debug

      - name: Upload Artifact Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/windows/bin
          if-no-files-found: warn

      - name: Upload Artifact MacOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@main
        with:
          name: macBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/macos/bin
          if-no-files-found: warn

      - name: Upload Artifact Windows
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild-${{matrix.sample}}
          path: samples/${{matrix.sample}}/export/linux/bin
          if-no-files-found: warn
